### ISSUE TITLE
Is it a better idea to replace 'SETNX' directive with ‘SET’?

### ISSUE THREAD

**Issue by nutshellfool** [josiahcarlson/redis-in-action#72] opened 2020-06-02 09:17 UTC
https://github.com/josiahcarlson/redis-in-action/blob/a5d1aa5c7506ffc7c3557b1c1543ed3029b84566/python/ch08_listing_source.py#L32

as the snippet show, try to add expire to given key is separate operation with setnx, so the chance is that the expire operation will not valid(maybe application crashed just before set expire).  

if 'SET' directive support ex and px parameter,  is it a better idea to use `SET` to replace `SETNX` and `EXPIRE` ?
```
def acquire_lock_with_timeout(
        conn, lockname, acquire_timeout=10, lock_timeout=10):
    identifier = str(uuid.uuid4())  # A
    lockname = 'lock:' + lockname
    lock_timeout = int(math.ceil(lock_timeout))  # D

    end = time.time() + acquire_timeout
    while time.time() < end:
        if conn.set(lockname, identifier, ex=lock_timeout, nx=True):
            return identifier

        # the following code are equivalence with Directive:
        #
        # set(key, value, ex=xx, nx=True)

        # if conn.setnx(lockname, identifier):  # B
        #     conn.expire(lockname, lock_timeout)  # B
        #     return identifier
        elif conn.ttl(lockname) < 0:  # C
            conn.expire(lockname, lock_timeout)  # C

        time.sleep(.001)

    return False
```

**Comment by josiahcarlson** [comment] 2020-06-07 03:04
The code snippets here are from the book (originally used to generate the code listings in the book). When the book was written, `set` did not have the option for both `nx` and `ex` at the same time. You could either `set`, `setnx`, or `setex`. You could not `set ... nx ex`. That was just not an option. Per the Redis docs, this was added in `2.6.12`, where as the book was released / written somewhere around 2.6.9.

In this case, these specific examples were also meant to show the different types of locks, their limitations, and how a person could *easily* mess them up if they weren't careful. It was as much a lesson on Redis, as it was on being careful.

Going to close this, because it's not a bug. Thank you, and good question!

**Closed by josiahcarlson** 2020-06-07 03:04 UTC
